-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguyC3ZLFnyIoSw87M
N6cmUEoxFcGjb/yDoZPm/sNADLWgCgYIKoZIzj0DAQehRANCAARvteqzqIkfvYcW
9uRk9ICgKErLll/bCe20wmFE91vC+hG29LZ5yBE4+i+P/vnNX/SqutHmMrx+fzBo
iUsiw6Ef
-----END PRIVATE KEY-----